/*
CREATED		2015/2/8
MODIFIED		2015/2/8
PROJECT		
MODEL		
COMPANY		
AUTHOR		
VERSION		
DATABASE		MYSQL 5 
*/




CREATE TABLE ARTICLE (
	ID BIGINT NOT NULL,
	CLASS BIGINT NOT NULL DEFAULT 0,
	TITLE VARCHAR(500) NOT NULL,
	TITLECOLOR VARCHAR(50),
	CONTENT TEXT,
	HITS INT NOT NULL DEFAULT 0,
	KEYWORD VARCHAR(200),
	LINKURL VARCHAR(500),
	SOURCE VARCHAR(80),
	AUTHOR VARCHAR(80),
	TITLEIMAGE VARCHAR(500),
	ISCHECKED CHAR(1) NOT NULL DEFAULT '1',
	ISIMGNEWS CHAR(1) NOT NULL DEFAULT '0',
	ISTOP CHAR(1) NOT NULL DEFAULT '0',
	ISRECOMMEND CHAR(1) NOT NULL DEFAULT '0',
	ISHOT CHAR(1) NOT NULL DEFAULT '0',
	ISDELETE CHAR(1) NOT NULL DEFAULT '0',
	ADDTIME DATETIME NOT NULL,
	UPTIME DATETIME NOT NULL,
	EDITUSERNAME VARCHAR(80) NOT NULL,
	CHECKUSERNAME VARCHAR(80),
 PRIMARY KEY (ID)) ;

CREATE TABLE ARTICLE_CLASSLIST (
	ID BIGINT NOT NULL,
	TITLE VARCHAR(200) NOT NULL,
	PARENT BIGINT NOT NULL DEFAULT 0,
	UPTIME DATETIME NOT NULL,
	ORDERNUM INT NOT NULL DEFAULT 1,
	ISSHOW CHAR(1) NOT NULL DEFAULT '1',
	ALLOWUSERS VARCHAR(100),
 PRIMARY KEY (ID)) ;

CREATE TABLE ROLES (
	ROLEID VARCHAR(50) NOT NULL,
	ROLENAME VARCHAR(50) NOT NULL,
	ROLEDESC VARCHAR(200),
	ORDERNUM INT NOT NULL DEFAULT 0,
 PRIMARY KEY (ROLEID)) ;

CREATE TABLE SYSTEMCONFIG (
	ID INT NOT NULL,
	CONFIG TEXT,
 PRIMARY KEY (ID)) ;

CREATE TABLE USERINROLE (
	USERID BIGINT NOT NULL,
	ROLEID VARCHAR(50) NOT NULL,
 PRIMARY KEY (USERID,ROLEID)) ;

CREATE TABLE USERS (
	USERID VARCHAR(50) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	USERPASSWORD VARCHAR(80) NOT NULL,
	PHONE VARCHAR(50),
	ISLOCK CHAR(1) NOT NULL,
	USERDESC VARCHAR(80),
	ADDTIME DATETIME NOT NULL,
	UPTIME DATETIME NOT NULL,
	LASTLOGINTIME DATETIME,
	LASTLOGINIP VARCHAR(50),
 PRIMARY KEY (USERID)) ;



CREATE INDEX CLASS ON ARTICLE (CLASS);
CREATE INDEX ID ON ARTICLE (ID);
CREATE INDEX KEYWORD ON ARTICLE (KEYWORD);
CREATE INDEX ID ON ARTICLE_CLASSLIST (ID);
CREATE INDEX ORDERNUM ON ARTICLE_CLASSLIST (ORDERNUM);






